# Generated by Django 5.0.6 on 2024-06-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='mend_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='mstart_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
