# Generated by Django 5.0.6 on 2024-06-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_remove_log_intime_remove_log_mintime'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='intime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='mintime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.UniqueConstraint(fields=('employee', 'intime'), name='employeeintime'),
        ),
    ]
