# Generated by Django 5.0.6 on 2024-06-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_log_intime_log_mintime_log_employeeintime'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
