# Generated by Django 5.0.6 on 2024-06-09 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(choices=[('Anik', 'Anik'), ('Akash', 'Akash'), ('Rahat', 'Rahat'), ('Jibon', 'Jibon'), ('Milon', 'Milon')], max_length=10)),
                ('intime', models.DateTimeField()),
                ('outtime', models.DateTimeField()),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift.shift')),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'intime', 'shift'), name='employeeintimeshift'),
        ),
    ]
