# Generated by Django 5.0.6 on 2024-06-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='employeeintimeshift',
        ),
    ]
