# Generated by Django 5.0.6 on 2024-06-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_attendance_shift'),
        ('shift', '0002_shift_mend_at_shift_mstart_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ManyToManyField(blank=True, to='shift.shift'),
        ),
    ]
