# Generated by Django 5.0.6 on 2024-06-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_shift'),
        ('shift', '0002_shift_mend_at_shift_mstart_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'intime'), name='attendance_employeeintime'),
        ),
    ]
